version: '3'
services:
    tcpserver:
        build: .
        ports:
            - "8081:8000"
    redis:
        image: "redis:alpine"
    db:
        image: "mysql:8.0"
        restart: always
        environment: 
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test_user"
            MYSQL_PASSWORD: "test_user"
            MYSQL_ROOT_PASSWORD: "root"
        ports: 
            - "3306:3306"
        expose: 
            - "3306"
        volumes:
            - my-db:/var/lib/mysql

volumes:
    my-db:


