version: '3'
services:
    redis:
        image: "redis:alpine"
        restart: always
        ports:
            - "6379:6379"
        expose:
            - "6379"
    db:
        image: "mysql:8.0"
        restart: always
        environment: 
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test_user"
            MYSQL_PASSWORD: "test_user"
            MYSQL_ROOT_PASSWORD: "root"
        ports: 
            - "3306:3306"
        expose: 
            - "3306"


