name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build HTTP Server
        run: go build -v cmd/httpserver/httpserver.go
      - name: Build TCP Server
        run: go build -v cmd/tcpserver/tcpserver.go
      - name: Build Picture Server
        run: go build -v cmd/pictureserver/pictureserver.go
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test
        run: go test -race -cover -coverprofile=coverage.out $(go list ./... | egrep  -v "vendor|integration-test")
      - name: Get Code Coverage
        run: bash coverage.sh coverage.out
