name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build HTTP Server
        run: go build -v cmd/httpServer/httpserver.go
      - name: Build TCP Server
        run: go build -v cmd/tcpServer/tcpserver.go
      - name: Build Picture Server
        run: go build -v cmd/pictureServer/pictureserver.go
      - name: Test
        run: go test -v ./...
