name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Pwd
        run: pwd
      - name: Build HTTP Server
        run: |
          cd cmd/httpServer/
          go build -v
      - name: Build TCP Server
        run: |
          pwd
          cd cmd/tcpServer/
          go build -v
      - name: Build Picture Server
        run: go build -v cmd/pictureServer/
  test:
    name: Test go packages
    runs-on: ubuntu-latest
    steps:
      - name: setup go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Run all unit tests
        run: go test -v -cover
